---
title: "CapstoneR"
author: "Yeva Avetisyan, Anush Aghinyan"
date: "2024-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(gplots)
library(ggpubr)
library(dplyr)
library(colorspace)
library(scales)
library(RColorBrewer)
library(viridis)
library(reshape2)
library(Rcpp)
library(tidyr)
library(ggthemes)
library(graphics)
library(GGally)
library(ggExtra)
library(foreign)
library(jsonlite)
```


## Reading the data

```{r }
data <- read.csv("C:/Users/User/Downloads/capstone/cleaned_data.csv")
```

```{r}
# technical adjustments
colnames(data)[which(names(data) == "Work.sphere")] <- "work_sphere"
colnames(data)[which(names(data) == "Start.Date")] <- "start_date"
colnames(data)[which(names(data) == "End.Date")] <- "end_date"
colnames(data)[which(names(data) == "DOB")] <- "dob"
colnames(data)[which(names(data) == "Sex")] <- "sex"
colnames(data)[which(names(data) == "Region")] <- "region"
colnames(data)[which(names(data) == "Claim.Code")] <- "claim_code"
colnames(data)[which(names(data) == "Claim.Status")] <- "claim_status"
colnames(data)[which(names(data) == "Illness.ICD.Code")] <- "illness_code"
colnames(data)[which(names(data) == "Illness.Category")] <- "illness_category"
colnames(data)[which(names(data) == "Claim.Amount")] <- "claim_amount"
colnames(data)[which(names(data) == "Contract.Longevity")] <- "contract_longevity"
colnames(data)[which(names(data) == "Age")] <- "age"
colnames(data)[which(names(data) == "BirthYear")] <- "byear"
colnames(data)[which(names(data) == "Short.Work.Sphere")] <- "short_work_sphere"


data$sex=factor(data$sex, levels = c("Female", "Male", "Unknown"))
data$claim_status=factor(data$claim_status, levels = c("Claim creation", "Initial", "Final claim confirmation", "Satisfied", "Unsatisfied", "Canceled"))


data$log_claim_amount <- log(data$claim_amount + 1)
```



# Demographic insights

```{r}
# Age distribution
ggplot(data, aes(x = age)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") + theme_classic() +
  labs(title = "Age Distribution", x = "Age", y = "Frequency")

# This plot visualizes the distribution of ages among the dataset.
```


```{r}
# Sex Distribution
ggplot(data, aes(x = sex)) + geom_bar(fill = "lightgreen", color = "black") + theme_classic() +
  labs(title = "Sex Distribution", x = "Sex", y = "Frequency")

# This plot visualizes the distribution of sexes (gender) within the dataset.
```



```{r}
# Distributional difference of Age and Sex
ggplot(data, aes(x = age, fill = sex)) + geom_density(alpha = 0.5) +
  theme_classic() +
  scale_x_continuous(limits = c(0,100)) + labs(x = "Age", title = "Distributional difference of Age and Sex", fill = "Sex")

# This plot shows the distributional differences of age between different sexes. It allows for the comparison of age distributions across genders.
```


```{r}
# Region Distribution
ggplot(data, aes(x = region)) +
  geom_bar(stat = 'count', fill = "salmon") +
  theme_classic() +
  labs(title = "Region Distribution", x = "Region", y = "Frequency") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(stat='count', aes(label=..count..), parse = FALSE, position = position_dodge(width = 0.9), vjust = -0.3, size = 3)

# This plot shows the distribution of individuals across different regions.
```


```{r}
# Work Sphere Distribution
ggplot(data, aes(x = short_work_sphere)) + geom_bar(fill = "orange") +
  theme_classic() +
  labs(title = "Work Sphere Distribution", x = "Work Sphere", y = "Frequency") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(stat='count', aes(label=..count..), parse = FALSE, position = position_dodge(width = 0.9), vjust = -0.2, size = 3)

# This plot visualizes the distribution of individuals across various work spheres.
```


## Healthcare Claims Analysis

```{r}
# Claim Amount Distribution
ggplot(data %>% filter(log_claim_amount > 0), aes(x = log_claim_amount)) +
  theme_classic() +
  geom_histogram(binwidth = 0.1, fill = "skyblue", color = "black") +
  labs(title = "Claim Amount Distribution", x = "Claim Amount", y = "Frequency")

# This plot shows the distribution of claim amounts.
```


```{r}
# Claim Status Distribution
ggplot(data, aes(x = claim_status)) +
  geom_bar(fill = "purple") + theme_classic() +
  labs(title = "Claim Status Distribution", x = "Claim Status", y = "Frequency") +
  geom_text(stat='count', aes(label=..count..), parse = FALSE, position = position_dodge(width = 0.9), vjust = -0.5, size = 4)

# This plot illustrates the distribution of claim statuses within the dataset.
```


```{r}
# Illness Category Distribution
ggplot(data, aes(x = illness_category)) +
  geom_bar(fill = "#CDF77A") + theme_classic() +
  labs(title = "Illness Category Distribution", x = "Illness Category", y = "Frequency") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(stat='count', aes(label=..count..), parse = FALSE, position = position_dodge(width = 0.9), vjust = -0.2, size = 2)

# This plot displays the distribution of individuals across different illness categories.
```



## Box plots

```{r}
# Claim amounts by sex
ggplot(data, aes(x = sex, y = log_claim_amount, fill = sex)) +
  geom_boxplot() +
  theme_classic() +
  labs(title = "Claim Amounts by Sex", x = "Sex",y = "Claim Amount", fill = "Sex")

# This plot presents the distribution of claim amounts categorized by gender.
```


```{r}
# Box plot of claim amounts by region
ggplot(data, aes(x = region, y = log_claim_amount, fill = region)) +
  geom_boxplot() +
  theme_classic() +
  labs(title = "Claim Amounts by Region", x = "Region", y = "Claim Amount", fill = "Region") +
  theme(axis.text.x = element_text(angle = 45))

# This plot presents the distribution of claim amounts across various regions.
```


```{r}
# Faceted plot of claim amounts by sex and claim status
ggplot(data %>% filter(claim_status %in% c("Claim creation", "Initial", "Satisfied")),
       aes(x = sex, y = log_claim_amount, fill = sex)) + geom_boxplot() +
  facet_grid(. ~ claim_status) +
  labs(title = "Claim Amounts by Sex and Claim Status", x = "Sex", y = "Claim Amount") +
  theme(axis.text.x = element_text(angle = 45)) + theme_classic()

# This plot illustrates the distribution of claim amounts across different sexes, segmented by claim status.
```



```{r}
# Claim Amounts by Region and Sex
ggplot(data, aes(x = region, y = claim_amount, fill = sex)) +
  geom_boxplot() + theme_classic () +
  facet_wrap(~ sex) +
  labs(title = "Claim Amounts by Region and Sex", x = "Region", y = "Claim Amount", fill = "Sex") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

# This plot shows the claim amounts by sex and region.
```



# Interesting insights

```{r}
# Top 5 illnesses
top_5_illnesses <- data %>%
      group_by(illness_category) %>%
      summarise(Count = n()) %>%
      top_n(5, Count)
    
    ggplot(top_5_illnesses, aes(x = reorder(illness_category, Count), y = Count, fill = illness_category)) +
      geom_bar(stat = "identity") +
      labs(title = "Top 5 Illnesses", x = "Illness", y = "Frequency", fill = "Illness category") +
      theme_classic() +
      coord_flip() +
      scale_fill_manual(values = c("#3333cc", "#cc00cc", "#ffcc00", "#00994d", "#4da6ff"))
    
# This plot showcases the top five most popular illnesses within the dataset.
```


```{r}
# Top work spheres visiting the eye doctor
top_work_eye_doctor <- data %>%
  filter(illness_category == "Ophthalmology") %>%
  group_by(short_work_sphere) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  top_n(3, Count)

ggplot(top_work_eye_doctor, aes(x = reorder(short_work_sphere, Count), y = Count, fill = short_work_sphere)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 3 Work Spheres Visiting the Eye Doctor", x = "Work Sphere", y = "Number of Visits", fill = "Work Sphere") +
  theme_classic() +
  coord_flip() +
  scale_fill_manual(values = c("#ff9933", "#bf80ff", "#33adff"))

# This plot presents the top work spheres or industries where individuals seek medical attention from eye doctors.
```



```{r}
# Top age groups with oncological claims
top_age_oncology <- data %>%
  filter(illness_category == "Oncology") %>%
  group_by(age) %>%
  summarise(Count = n()) %>%
  arrange(age) %>%
  top_n(5, Count)

ggplot(top_age_oncology, aes(x = factor(age), y = Count, fill = as.factor(age))) +
  geom_col() +
  labs(title = "Top Age Groups with Oncological Claims", x = "Age Group", y = "Frequency", fill = "Age Group") +
  theme_classic() +
  scale_fill_manual(values = c("#b3003b", "#0066cc", "#e6b800", "#339933", "#2e2eb8"))

# This plot visualizes the top age groups with oncological claims.
```


```{r}
# Top age groups with dental claims
top_age_dentistry <- data %>%
  filter(illness_category == "Dentistry") %>%
  group_by(age) %>%
  summarise(Count = n()) %>%
  arrange(age) %>%
  top_n(5, Count)

ggplot(top_age_dentistry, aes(x = factor(age), y = Count, fill = as.factor(age))) +
  geom_col() +
  labs(title = "Top Age Groups with Dental Claims", x = "Age Group", y = "Frequency", fill = "Age Group") +
  theme_classic() + scale_fill_manual(values = c("#ff7733", "#b30059", "#0099cc", "#669900", "#cccc00"))

# This plot displays the top age groups with dental claims.
```

```{r}
# Cases of Males with Gynecology Claims
male_gynecology_cases <- data %>%
  filter(illness_category == "Gynecology")
  
ggplot(male_gynecology_cases, aes(x = sex, fill = illness_category)) +
  geom_bar() + theme_classic() +
  labs(title = "Cases of Males with Gynecology Claims", x = "Sex", y = "Frequency", fill = "Illness Category") +
  scale_fill_manual(values = "#b30059")

# This plot visualizes cases of Gynecology Claims where Male individuals are present too.
```


```{r}
# Cases of Females with Urology Claims
female_urology_cases <- data %>%
  filter(illness_category == "Urology")
  
ggplot(female_urology_cases, aes(x = sex, fill = illness_category)) +
  geom_bar() + theme_classic() +
  labs(title = "Cases of Females with Urology Claims", x = "Sex", y = "Frequency", fill = "Illness Category") +
  scale_fill_manual(values = "#005ce6")

# This plot shows cases Urology Claims where Female individuals are present too.
```

```{r}
# Cases of Males with Pregnancy Claims
male_pregnancy_cases <- data %>%
  filter(illness_category == "Pregnancy")
  
ggplot(male_pregnancy_cases, aes(x = sex, fill = illness_category)) +
  geom_bar() + theme_classic() +
  labs(title = "Cases of Males with Pregnancy Claims", x = "Sex", y = "Frequency", fill = "Illness Category") +
  scale_fill_manual(values = "#e68a00")

# This plot visualizes cases of Pregnancy Claims where Male individuals are present too.
```

